#!/usr/bin/env bash
# Builds (or loads) the Sensor image, brings up the verification containers,
# runs `kestrelynx sensor --probe` against them with the same runtime flags
# docker-compose.sensor-probe.yml documents (real cap_add/seccomp/user/
# pid:host/network_mode:none), and saves the results — meant to be run the
# same way on a developer machine and on a VPS.
#
# This uses plain `docker build`/`docker run`, not `docker compose`:
# `docker compose` is a separate CLI plugin (or standalone binary) that is
# not guaranteed to be installed, or to be functional, on every host this
# runs on, while the Docker daemon and the plain `docker` CLI always are.
# Depending on compose here would add a failure mode this script does not
# need. docker-compose.sensor-probe.yml remains the readable reference for
# the same configuration and works with `docker compose up` wherever
# compose itself is available.
#
# --- Production safety (read this before changing target selection) -------
#
# This script never touches any container or volume it did not itself
# create in this run, and never reuses a name across runs. The mechanisms
# that make that true, and that a change to any of them needs to preserve:
#
#   1. The run ID is always generated by this script (generate_run_id) —
#      there is no flag or environment variable a caller can use to inject
#      one — and is validated (run_id_is_valid: 1-64 characters,
#      alphanumeric and hyphen only) both right after generation and again
#      by every script that receives it, before it is ever substituted into
#      a resource name or Docker label.
#   2. Every container and volume this script or probe-targets.sh creates
#      is named with that run ID (see lib-ledger.sh) and carries a
#      `kestrelynx.probe-run=<run ID>` Docker label. The name is recorded in
#      $LEDGER immediately before the creating command runs, and the
#      resolved container ID (or the volume's own name) is recorded right
#      after, via ledger_run_container/ledger_create_volume — never after
#      the fact, and never only after success.
#   3. Cleanup (the `cleanup` trap below, via ledger_cleanup) NEVER removes
#      a ledger-recorded name on the strength of the name alone: it
#      `docker inspect`s the resource first and only acts if the inspected
#      kestrelynx.probe-run label matches this run's own ID, and for a
#      container, stops/removes it by the exact ID that same inspect call
#      returned — never by name again — so a name reused by a different
#      container between the check and the removal cannot be affected. A
#      name that exists but carries a different (or no) label — the
#      "someone else's resource happens to share this run's generated
#      name" case — is left untouched and reported as a warning, never
#      stopped or removed. A `docker inspect`/`volume ls` failure while
#      checking is likewise never treated as "safe to remove" or as "does
#      not exist" (see lib-ledger.sh's inspect_owner_label and
#      inspect_owner_label_and_id).
#   4. This script confirms the Docker daemon itself is reachable (see
#      require_docker_daemon) before doing anything else, and refuses to
#      proceed if it is not — a daemon-connectivity failure partway through
#      a later check (e.g. probe-targets.sh's existing-volume check) is
#      never treated as "the thing being checked does not exist".
#   5. Of the containers probe-targets.sh creates, only TARGET_PID_KINDS (a
#      strict subset — sameuid/sockets/setuid/ext4vol) ever has its PID
#      resolved into a --target-pid argument, which is what makes
#      cmd/kestrelynx/sensor.go attempt any write/connect/signal/exec probe
#      against it at all. execloop/unconfined/privileged are deliberately
#      left out — read-only only. The sensor binary itself re-verifies, at
#      the moment it runs (not from this script's possibly-stale
#      docker inspect snapshot alone), that a --target-pid's current cgroup,
#      starttime, and probe-run/probe-kind labels all agree before running
#      any unsafe probe against it — see verifyTarget in
#      cmd/kestrelynx/sensor.go and that command's own package doc comment.
#   6. The cleanup trap is installed right after $LEDGER is created (empty),
#      before the build/load step: a `docker load` or `docker build`
#      failure creates no container or volume, so ledger_cleanup on an
#      empty ledger removes nothing — but the same trap also owns cleaning
#      up $LOAD_STAGE (a plain temp directory, not a Docker resource; see
#      the --image-tar branch), which does need to exist from the moment it
#      is created. Once installed, the trap fires on every exit path —
#      normal completion, an error under `set -e`, or a signal (e.g. Ctrl-C
#      sent to this script) — and verifies its own result afterward (see
#      ledger_verify_removed) rather than assuming success.
#   7. `docker volume create` reuses an existing volume of the same name
#      instead of failing if one appears between probe-targets.sh's own
#      existing-volume check and the create call itself — a documented CLI
#      behavior, not a bug. probe-targets.sh re-checks the created volume's
#      own ownership label immediately afterward, before anything mounts
#      it, and aborts rather than mounting a volume it does not own.
#   8. Every `docker run` this script or probe-targets.sh backgrounds (see
#      ledger_run_container) is tracked (KL_PENDING_RUN_PIDS) so that, before
#      the final ledger pass, this script's own cleanup waits for any of
#      them still in flight to actually finish — including probe-targets.sh
#      itself, which this script runs as a tracked child it signals and
#      waits for if this script is the one that gets signaled. Without this,
#      a creation already under way could complete after cleanup already
#      ran, leaving a resource nothing ever removes.
#
#   No production service is stopped, restarted, or signaled by this script
#   at any point.
#
# Usage:
#   deploy/docker/run-probe.sh [--variant full|no-bpf-caps|simulate-attach-failure|all] \
#     [--image-tar PATH] [output-dir]
#
#   --variant       which capability variant(s) to run the probe as
#                     full                    cap_add SYS_PTRACE,DAC_READ_SEARCH,
#                                             BPF,PERFMON (the real deployment's
#                                             cap_add list)
#                     no-bpf-caps             cap_add SYS_PTRACE,DAC_READ_SEARCH only
#                                             — exercises the "BPF/PERFMON not
#                                             granted" path: the file-capability
#                                             exec must still succeed (+p, not
#                                             +ep — see the Dockerfile), and the
#                                             probe must report eBPF unavailable
#                                             (reason "permission")
#                     simulate-attach-failure full cap_add, but passes
#                                             --simulate-ebpf-attach-failure to
#                                             the probe, forcing a genuine
#                                             partial-attach failure partway
#                                             through the five eBPF attach
#                                             points, to confirm clean unwind
#                                             and continued operation without
#                                             eBPF (reason "attach_failed")
#                     all                     all three, in one invocation
#                                             (default)
#   --image-tar     load this bundle (see save-images.sh) with `docker load`
#                     instead of building; skips the Go build entirely, for a
#                     host (e.g. a production VPS) where a 15-20 minute build
#                     is undesirable. The bundle's manifest (required tags,
#                     no duplicates, valid ID format) is validated before
#                     loading, and every loaded image's actual ID is checked
#                     against it afterward; every container this script or
#                     probe-targets.sh starts then runs from the verified ID,
#                     not the bare tag.
#   output-dir      defaults to a fresh directory under /tmp
#
# Requires: docker, python3. Does not require sudo unless the Docker daemon
# itself does on this host.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=lib-ledger.sh
source "$SCRIPT_DIR/lib-ledger.sh"

SENSOR_IMAGE_TAG="kestrelynx-sensor-probe:local"
TARGET_IMAGE_TAG="python:3.12.7-slim-bookworm" # keep in sync with probe-targets.sh's IMAGE default
SECCOMP_PROFILE="$SCRIPT_DIR/sensor-seccomp.json"
TARGETS_SH="$SCRIPT_DIR/probe-targets.sh"

VARIANT="all"
IMAGE_TAR=""
OUT_DIR=""
while [ $# -gt 0 ]; do
	case "$1" in
	--variant)
		VARIANT="$2"
		shift 2
		;;
	--variant=*)
		VARIANT="${1#--variant=}"
		shift
		;;
	--image-tar)
		IMAGE_TAR="$2"
		shift 2
		;;
	--image-tar=*)
		IMAGE_TAR="${1#--image-tar=}"
		shift
		;;
	-h | --help)
		sed -n '2,100p' "$0" | sed 's/^# \{0,1\}//'
		exit 0
		;;
	-*)
		echo "run-probe.sh: unknown flag $1" >&2
		exit 2
		;;
	*)
		if [ -n "$OUT_DIR" ]; then
			echo "run-probe.sh: unexpected extra argument $1" >&2
			exit 2
		fi
		OUT_DIR="$1"
		shift
		;;
	esac
done

case "$VARIANT" in
all) VARIANTS=(full no-bpf-caps simulate-attach-failure) ;;
full) VARIANTS=(full) ;;
no-bpf-caps) VARIANTS=(no-bpf-caps) ;;
simulate-attach-failure) VARIANTS=(simulate-attach-failure) ;;
*)
	echo "run-probe.sh: unknown --variant $VARIANT (want: full, no-bpf-caps, simulate-attach-failure, all)" >&2
	exit 2
	;;
esac

# require_docker_daemon aborts immediately if the Docker daemon cannot be
# reached, rather than letting a later, unrelated check (e.g.
# probe-targets.sh's existing-volume check) misinterpret that as "the thing
# being checked does not exist".
require_docker_daemon() {
	local out
	if ! out="$(docker info 2>&1)"; then
		echo "run-probe.sh: cannot reach the Docker daemon; aborting before creating anything. docker info said:" >&2
		echo "$out" >&2
		exit 1
	fi
}
require_docker_daemon

# generate_run_id produces a value unique enough that two invocations of
# this script (even concurrent ones) get different resource names: wall
# clock to the second, this shell's own PID, and $RANDOM. It is not a
# security token — only a naming/ownership discriminator, and ownership
# itself is enforced by the Docker label every resource carries, not by the
# ID's unguessability — so this amount of entropy is sufficient. There is no
# flag or environment variable to override this: see this file's own
# "Production safety" note above for why an externally supplied run ID
# (arbitrary bytes a caller controls) must never reach a ledger line or a
# `docker run`/`docker volume create` argument unvalidated.
generate_run_id() { echo "$(date +%Y%m%d%H%M%S)-$$-${RANDOM}"; }

RUN_ID="$(generate_run_id)"
if ! run_id_is_valid "$RUN_ID"; then
	echo "run-probe.sh: internal error: generated run ID \"$RUN_ID\" failed validation; refusing to proceed" >&2
	exit 1
fi
echo "run-probe.sh: run ID $RUN_ID" >&2

OUT_DIR="${OUT_DIR:-$(mktemp -d /tmp/kestrelynx-probe.XXXXXX)}"
mkdir -p "$OUT_DIR"
OUT_DIR="$(cd "$OUT_DIR" && pwd)"
echo "run-probe.sh: results will be collected under $OUT_DIR" >&2

IN_DIR="$OUT_DIR/in"
mkdir -p "$IN_DIR"
LEDGER="$OUT_DIR/ledger.txt"
: >"$LEDGER" # truncate/create; ledger_append only ever appends after this

# --- Preflight -------------------------------------------------------------
PREFLIGHT="$OUT_DIR/preflight.txt"
ARCH="$(uname -m)"
{
	echo "date: $(date -u +%FT%TZ)"
	echo "run_id: $RUN_ID"
	echo "arch: $ARCH"
	echo "docker version:"
	docker version --format '{{json .}}' 2>&1 || true
	echo
	echo "docker info (relevant fields):"
	docker info --format 'CgroupDriver={{.CgroupDriver}} CgroupVersion={{.CgroupVersion}} OperatingSystem={{.OperatingSystem}} KernelVersion={{.KernelVersion}}' 2>&1 || true
	echo
	echo "kernel: $(uname -a)"
	echo
	if [ -e /sys/kernel/security/apparmor/profiles ]; then
		echo "apparmor: present"
		echo "apparmor profiles (first 20 lines):"
		head -20 /sys/kernel/security/apparmor/profiles 2>&1 || true
	else
		echo "apparmor: not present (/sys/kernel/security/apparmor/profiles missing)"
	fi
	echo
	echo "cgroup mount type: $(stat -f -c '%T' /sys/fs/cgroup 2>&1 || true)"
	echo
	echo "BTF readable: $([ -r /sys/kernel/btf/vmlinux ] && echo yes || echo no)"
} >"$PREFLIGHT"
echo "run-probe.sh: preflight recorded in $PREFLIGHT" >&2
cat "$PREFLIGHT" >&2

# save-images.sh only ever builds for linux/amd64 (see that script): a
# bundle it produced loaded on a non-amd64 host would silently run under
# emulation at best, or fail to run at all — refuse outright rather than
# guess.
if [ -n "$IMAGE_TAR" ] && [ "$ARCH" != "x86_64" ]; then
	echo "run-probe.sh: --image-tar was built for amd64 (x86_64) by save-images.sh, but this host reports arch $ARCH; refusing to load a mismatched image" >&2
	exit 1
fi

if [ ! -f "$SECCOMP_PROFILE" ]; then
	echo "run-probe.sh: $SECCOMP_PROFILE not found; generate it first (scripts/gen_sensor_seccomp_profile.py)" >&2
	exit 1
fi

# --- Cleanup trap: installed now, right after $LEDGER exists (empty) and
# before anything else — see "Production safety" point 6 above. Cleaning up
# an empty ledger is a no-op, so this being active during build/load is
# harmless; what it must be active for is $LOAD_STAGE (set below, in the
# --image-tar branch) and every Docker resource created from here on. ------
LOAD_STAGE=""
CLEANED_UP=0
TARGETS_PID=""
cleanup() {
	if [ "$CLEANED_UP" = "1" ]; then
		return
	fi
	CLEANED_UP=1
	if [ -n "$LOAD_STAGE" ] && [ -d "$LOAD_STAGE" ]; then
		rm -rf "$LOAD_STAGE"
	fi
	# If probe-targets.sh (backgrounded below so its PID is trackable here)
	# is still running — e.g. this process itself received a signal
	# targeted only at it, leaving that child to keep going on its own —
	# wait for it to finish before touching the ledger, so nothing it
	# started is still in flight when the ledger is read.
	# Only `wait` is used here, never a signal: `wait` acts solely on this
	# shell's own not-yet-reaped child, so a PID number that has since been
	# reaped and reused by an unrelated process is never touched. The
	# creation process is left to finish on its own; everything it creates
	# is in the ledger and is removed below once it has exited.
	if [ -n "$TARGETS_PID" ]; then
		echo "run-probe.sh: waiting for the verification-target creation process (pid $TARGETS_PID) to finish before cleaning up" >&2
		wait "$TARGETS_PID" 2>/dev/null || true
		TARGETS_PID=""
	fi
	# Every `docker run` this process itself backgrounded directly (via
	# ledger_run_container — the fcap-check/fcap-read/sensor-probe/
	# sensor-read containers) the same way, in case one was still in flight.
	ledger_wait_pending
	echo "run-probe.sh: cleaning up run $RUN_ID's resources" >&2
	local ledger_status=0
	ledger_cleanup "$LEDGER" "$RUN_ID" || ledger_status=$?
	if [ "$ledger_status" = 3 ]; then
		echo "run-probe.sh: cleanup ABORTED — the ledger itself was malformed; see above for what may need manual removal" >&2
		return
	fi
	if ledger_verify_removed "$LEDGER" "$RUN_ID"; then
		echo "run-probe.sh: cleanup verified (every resource run $RUN_ID owns is gone)" >&2
	else
		local verify_status=$?
		if [ "$verify_status" = 2 ]; then
			echo "run-probe.sh: cleanup NOT verified — a check against the Docker daemon itself failed; inspect $LEDGER and the daemon manually" >&2
		else
			echo "run-probe.sh: WARNING: cleanup incomplete — some of run $RUN_ID's resources are still present; see $LEDGER" >&2
		fi
	fi
}
trap cleanup EXIT

# --- Build or load -----------------------------------------------------
if [ -n "$IMAGE_TAR" ]; then
	echo "run-probe.sh: loading prebuilt image(s) from $IMAGE_TAR (no build, no registry access needed)" >&2
	LOAD_STAGE="$(mktemp -d)"
	tar -xf "$IMAGE_TAR" -C "$LOAD_STAGE" images.tar manifest.txt

	# --- Validate the manifest before trusting anything in it: required
	# tags present, no duplicates, and each ID well-formed. An empty or
	# incomplete manifest is a hard failure, not a vacuous "everything
	# matched".
	MANIFEST="$LOAD_STAGE/manifest.txt"
	declare -A manifest_ids=()
	manifest_lines=0
	while read -r m_tag m_id; do
		[ -n "$m_tag" ] || continue
		manifest_lines=$((manifest_lines + 1))
		if [ -n "${manifest_ids[$m_tag]:-}" ]; then
			echo "run-probe.sh: manifest.txt lists tag $m_tag more than once; refusing to trust it" >&2
			exit 1
		fi
		if ! [[ "$m_id" =~ ^sha256:[0-9a-f]{64}$ ]]; then
			echo "run-probe.sh: manifest.txt has a malformed image ID for $m_tag: \"$m_id\"" >&2
			exit 1
		fi
		manifest_ids[$m_tag]="$m_id"
	done <"$MANIFEST"
	if [ "$manifest_lines" -eq 0 ]; then
		echo "run-probe.sh: manifest.txt in $IMAGE_TAR is empty; refusing to proceed" >&2
		exit 1
	fi
	for required in "$SENSOR_IMAGE_TAG" "$TARGET_IMAGE_TAG"; do
		if [ -z "${manifest_ids[$required]:-}" ]; then
			echo "run-probe.sh: manifest.txt in $IMAGE_TAR does not list the required tag $required" >&2
			exit 1
		fi
	done

	docker load -i "$LOAD_STAGE/images.tar" 2>&1 | tee "$OUT_DIR/build.log" >&2

	# Cross-check every manifest-listed image against what was actually
	# loaded, then switch to referencing images by their verified ID (not
	# the bare tag) for every container this script or probe-targets.sh
	# starts from here on — a tag can be reassigned; a content ID cannot.
	for tag in "${!manifest_ids[@]}"; do
		got_id="$(docker image inspect -f '{{.Id}}' "$tag" 2>&1)" || {
			echo "run-probe.sh: $tag not present after docker load (listed in $IMAGE_TAR's manifest)" >&2
			exit 1
		}
		if [ "$got_id" != "${manifest_ids[$tag]}" ]; then
			echo "run-probe.sh: image ID mismatch for $tag after docker load: manifest says ${manifest_ids[$tag]}, got $got_id — refusing to proceed" >&2
			exit 1
		fi
	done
	SENSOR_IMAGE="${manifest_ids[$SENSOR_IMAGE_TAG]}"
	export KL_PROBE_TARGET_IMAGE="${manifest_ids[$TARGET_IMAGE_TAG]}"
	echo "run-probe.sh: loaded image(s) match the bundle's manifest; using verified image IDs from here on" >&2

	rm -rf "$LOAD_STAGE"
	LOAD_STAGE=""
else
	echo "run-probe.sh: building the Sensor image" >&2
	docker build -t "$SENSOR_IMAGE_TAG" -f "$REPO_ROOT/Dockerfile" "$REPO_ROOT" 2>&1 | tee "$OUT_DIR/build.log" >&2
	SENSOR_IMAGE="$SENSOR_IMAGE_TAG"
fi

# --- Verify the file capability survived into the image -------------------
# setcap's xattr must still be effective on the binary once the image
# actually runs it, checked by running the real binary with the real
# cap_add set (not by extracting the file and checking its xattr on the
# host, which does not reproduce the exec-time behavior this depends on).
FCAP_CHECK="$OUT_DIR/file-capability.txt"
FCAP_DIR="$OUT_DIR/fcap-check"
mkdir -p "$FCAP_DIR/out" "$FCAP_DIR/in"
chmod 0777 "$FCAP_DIR/out"
echo '[]' >"$FCAP_DIR/in/inspect.json"
ledger_run_container "$LEDGER" "$RUN_ID" "kl-fcap-check-$RUN_ID" --rm \
	--entrypoint kestrelynx-sensor \
	--cap-drop ALL \
	--cap-add SYS_PTRACE --cap-add DAC_READ_SEARCH --cap-add BPF --cap-add PERFMON \
	--user 65532:65532 \
	-v "$FCAP_DIR/out:/out" \
	-v "$FCAP_DIR/in:/inspect:ro" \
	"$SENSOR_IMAGE" \
	sensor --probe --out /out/probe-report.json --inspect-json /inspect/inspect.json --run-id "$RUN_ID" --listen-events 0s \
	>"$OUT_DIR/fcap-check.log" 2>&1 || true

# Read back through a throwaway root container, not directly as this
# script's own user: the probe wrote the file as UID 65532 mode 0600, which
# this script's own (usually different, non-root) user cannot open. The
# parser script is passed as a -c string, not a heredoc on python3's own
# stdin, so stdin stays free to carry the piped JSON.
ledger_run_container "$LEDGER" "$RUN_ID" "kl-fcap-read-$RUN_ID" --rm \
	--entrypoint cat -v "$FCAP_DIR/out:/out" "$SENSOR_IMAGE" /out/probe-report.json 2>/dev/null |
	python3 -c '
import json, sys
report = json.load(sys.stdin)
caps = report.get("startup", {}).get("capabilities", {})
for name in ("CAP_SYS_PTRACE", "CAP_DAC_READ_SEARCH", "CAP_BPF", "CAP_PERFMON"):
    c = caps.get(name, {})
    permitted, raised, error = c.get("permitted_at_start"), c.get("raised_effective"), c.get("error")
    print(f"{name}: permitted_at_start={permitted} raised_effective={raised} error={error}")
' >"$FCAP_CHECK" 2>&1 || true
cat "$FCAP_CHECK" >&2

# --- Bring up verification targets (once, shared by every variant) --------
export KL_PROBE_RUN_ID="$RUN_ID"
export KL_PROBE_LEDGER="$LEDGER"
echo "run-probe.sh: starting verification containers" >&2
# Backgrounded (rather than a plain foreground call) so TARGETS_PID is
# something cleanup() can act on if this process is itself signaled while
# probe-targets.sh is still running — see cleanup's own comment. The
# immediate `wait` below makes this behave exactly like a foreground call on
# every other path: this line still does not return, and still does not
# mask probe-targets.sh's own exit status, until it finishes normally.
"$TARGETS_SH" up &
TARGETS_PID=$!
# Stop tracking the PID as soon as it has been reaped, on both the success
# and the failure path, so cleanup never acts on a number that may already
# belong to another process.
if wait "$TARGETS_PID"; then
	TARGETS_PID=""
else
	targets_status=$?
	TARGETS_PID=""
	exit "$targets_status"
fi

# --- Inspect --------------------------------------------------------------
KINDS=(sameuid sockets setuid ext4vol execloop unconfined privileged)
PRESENT_NAMES=()
for k in "${KINDS[@]}"; do
	n="kl-probe-$k-$RUN_ID"
	if docker inspect "$n" >/dev/null 2>&1; then
		PRESENT_NAMES+=("$n")
	fi
done
docker inspect "${PRESENT_NAMES[@]}" >"$IN_DIR/inspect.json"
echo "run-probe.sh: inspected ${#PRESENT_NAMES[@]} verification containers into $IN_DIR/inspect.json" >&2

# --- Report the ext4-volume container's actual backing filesystem, rather
# than assuming it matches its name: this run's own record should say what
# it actually measured, not what it expected.
VOLUME_MOUNTPOINT="$(docker volume inspect "kl-probe-ext4vol-data-$RUN_ID" --format '{{.Mountpoint}}' 2>/dev/null || true)"
if [ -n "$VOLUME_MOUNTPOINT" ]; then
	echo "kl-probe-ext4vol-data-$RUN_ID backing filesystem: $(stat -f -c '%T' "$VOLUME_MOUNTPOINT" 2>&1 || true)" | tee -a "$PREFLIGHT" >&2
fi

# --- Resolve the four target PIDs the probe is allowed to run
# write/connect/signal/exec probes against (all labeled probe-target=true
# with a probe-kind label; execloop/unconfined/privileged are deliberately
# excluded — read-only only, per this script's own doc comment). This list
# is drawn only from PRESENT_NAMES, itself drawn only from this run's own
# $RUN_ID-qualified names — never from a general listing of running
# containers.
TARGET_PID_KINDS=(sameuid sockets setuid ext4vol)
mapfile -t TARGET_PIDS < <(python3 - "$IN_DIR/inspect.json" "$RUN_ID" "${TARGET_PID_KINDS[@]}" <<'PY'
import json, sys
path, run_id, wanted_kinds = sys.argv[1], sys.argv[2], set(sys.argv[3:])
wanted_names = {f"kl-probe-{k}-{run_id}" for k in wanted_kinds}
with open(path) as f:
    data = json.load(f)
for entry in data:
    name = entry.get("Name", "").lstrip("/")
    if name in wanted_names:
        print(entry["State"]["Pid"])
PY
)
echo "run-probe.sh: target PIDs for unsafe-op probes: ${TARGET_PIDS[*]:-<none resolved>}" >&2

TARGET_ARGS=()
for pid in "${TARGET_PIDS[@]:-}"; do
	[ -n "$pid" ] && TARGET_ARGS+=(--target-pid "$pid")
done

# --- Summary helper ---------------------------------------------------
cat >"$OUT_DIR/summarize.py" <<'PY'
import json, sys

report = json.load(open(sys.argv[1]))
caps = report.get("startup", {}).get("capabilities", {})
for name in ("CAP_SYS_PTRACE", "CAP_DAC_READ_SEARCH", "CAP_BPF", "CAP_PERFMON"):
    c = caps.get(name, {})
    print(f"  {name}: permitted_at_start={c.get('permitted_at_start')} "
          f"raised_effective={c.get('raised_effective')} "
          f"confirmed_gone_after_drop={c.get('confirmed_gone_after_drop')}")

fdcheck = report.get("startup", {}).get("parser_bpf_fd_check", {})
print(f"  parser_bpf_fd_check: status={fdcheck.get('status')} "
      f"inherited_count={fdcheck.get('inherited_count')} reason={fdcheck.get('reason')}")

sc = report.get("self_check") or {}
print(f"  self_check: Failed={sc.get('Failed')} Degraded={sc.get('Degraded')}")
if report.get("self_check_error"):
    print(f"  self_check_error: {report.get('self_check_error')}")

ebpf = report.get("ebpf", {})
print(f"  ebpf: attempted={ebpf.get('attempted')} loaded={ebpf.get('loaded')} "
      f"status={ebpf.get('status')} reason={ebpf.get('reason')} error={ebpf.get('error')}")
print(f"  ebpf connected_seconds={ebpf.get('connected_seconds')}")

print(f"  denied_ops_summary: {report.get('denied_ops_summary')}")
print(f"  unsafe_ops_summary: {report.get('unsafe_ops_summary')}")
print(f"  config_errors: {report.get('config_errors')}")
print(f"  warnings: {report.get('warnings')}")

execloop = [e for e in ebpf.get("sampled_events", []) if e.get("container", "").startswith("kl-probe-execloop-")]
print(f"  kl-probe-execloop sampled events: {len(execloop)}")
for e in execloop[:5]:
    print(f"    kind={e.get('kind')} path={e.get('path')!r} "
          f"path_looks_container_relative={e.get('path_looks_container_relative')}")

for c in report.get("containers", []):
    if c.get("cgroup_dir_inode"):
        print(f"  container {c.get('name')}: cgroup_dir_inode={c.get('cgroup_dir_inode')} "
              f"events_cgroup_id_confirmed={c.get('events_cgroup_id_confirmed')}")
PY

# --- Run the probe, once per requested variant -----------------------
for variant in "${VARIANTS[@]}"; do
	VARIANT_OUT_DIR="$OUT_DIR/out-$variant"
	mkdir -p "$VARIANT_OUT_DIR"
	# The probe container runs as UID 65532, not this script's own user; the
	# output directory must be writable by it regardless of who invokes this
	# script.
	chmod 0777 "$VARIANT_OUT_DIR"

	EXTRA_PROBE_ARGS=()
	case "$variant" in
	full)
		CAP_ADD_ARGS=(--cap-add SYS_PTRACE --cap-add DAC_READ_SEARCH --cap-add BPF --cap-add PERFMON)
		;;
	no-bpf-caps)
		# Exercises the "BPF/PERFMON not granted" path: the setcap'd
		# binary's file capability is +p only (see the Dockerfile), so
		# exec must still succeed even though the container's bounding
		# set lacks two of the four named capabilities; the probe must
		# then report eBPF unavailable rather than failing outright.
		CAP_ADD_ARGS=(--cap-add SYS_PTRACE --cap-add DAC_READ_SEARCH)
		;;
	simulate-attach-failure)
		CAP_ADD_ARGS=(--cap-add SYS_PTRACE --cap-add DAC_READ_SEARCH --cap-add BPF --cap-add PERFMON)
		EXTRA_PROBE_ARGS=(--simulate-ebpf-attach-failure)
		;;
	esac

	echo "run-probe.sh: running kestrelynx sensor --probe (variant: $variant)" >&2
	# Flags mirror docker-compose.sensor-probe.yml's service definition
	# exactly (pid:host -> --pid host, cgroup:host -> --cgroupns host, and
	# so on) aside from the per-variant cap_add list above; see that file
	# for the rationale behind each one.
	ledger_run_container "$LEDGER" "$RUN_ID" "kl-sensor-probe-$RUN_ID-$variant" --rm \
		--entrypoint kestrelynx-sensor \
		--pid host \
		--cgroupns host \
		--network none \
		--cap-drop ALL \
		"${CAP_ADD_ARGS[@]}" \
		--security-opt "seccomp=$SECCOMP_PROFILE" \
		--user 65532:65532 \
		--read-only \
		-v "$VARIANT_OUT_DIR:/out" \
		-v "$IN_DIR:/inspect:ro" \
		"$SENSOR_IMAGE" \
		sensor --probe \
		--out /out/probe-report.json \
		--inspect-json /inspect/inspect.json \
		--listen-events 8s \
		--run-id "$RUN_ID" \
		"${EXTRA_PROBE_ARGS[@]}" \
		"${TARGET_ARGS[@]}" 2>&1 | tee "$OUT_DIR/probe-run-$variant.log" >&2

	READABLE="$OUT_DIR/probe-report-$variant.json"
	if [ -f "$VARIANT_OUT_DIR/probe-report.json" ]; then
		# Same reasoning as the fcap-check read-back above: the report is
		# UID 65532 mode 0600, unreadable by this script's own user.
		ledger_run_container "$LEDGER" "$RUN_ID" "kl-sensor-read-$RUN_ID-$variant" --rm \
			--entrypoint cat -v "$VARIANT_OUT_DIR:/out" "$SENSOR_IMAGE" /out/probe-report.json >"$READABLE" 2>/dev/null || true
	fi
	if [ -s "$READABLE" ]; then
		echo "run-probe.sh: probe report (variant $variant) at $READABLE" >&2
		echo "run-probe.sh: summary (variant $variant):" >&2
		python3 "$OUT_DIR/summarize.py" "$READABLE" >&2
	else
		echo "run-probe.sh: WARNING: no readable probe report for variant $variant; see $OUT_DIR/probe-run-$variant.log" >&2
	fi
done

echo "run-probe.sh: done. Collected files:" >&2
echo "  $PREFLIGHT" >&2
echo "  $OUT_DIR/build.log" >&2
echo "  $FCAP_CHECK" >&2
echo "  $IN_DIR/inspect.json" >&2
echo "  $LEDGER" >&2
for variant in "${VARIANTS[@]}"; do
	echo "  $OUT_DIR/probe-run-$variant.log" >&2
	echo "  $OUT_DIR/probe-report-$variant.json (if produced)" >&2
done
