// Package ebpf loads and runs the Sensor's CO-RE BPF programs: the
// observer's own view of process execution and executable-mapping activity,
// obtained without tracefs and without an external exec (see bpf/kestrelynx.c
// for what each attach point captures and why).
//
// The package owns three things: the BPF C source and the objects bpf2go
// compiles from it (regenerated by gen.sh, which needs Docker and bpftool;
// see that script for why), a loader that creates the maps and ring buffer,
// writes the Sensor's own cgroup ID into the exclusion map, and attaches all
// five programs before returning anything usable, and a decoder that turns
// ring buffer records into the Go Event type. It does not decide what to do
// with events, does not build the cgroup-to-container correspondence table,
// and does not drop privileges: deciding what an event means for a package's
// usage state belongs to the code that consumes Handle.Read, the
// cgroup-to-container table belongs to that same consumer, and dropping
// CAP_BPF/CAP_PERFMON is the process-wide sandboxing package's job, not
// this one's. Load returns an error unwinding everything it created if any
// step fails, and Handle exposes only the maps and ring buffer reader
// needed once loading and attaching have succeeded and capabilities have
// been dropped elsewhere: only map operations on already-open file
// descriptors remain possible at that point, and Handle's API reflects
// that on purpose rather than offering to load or attach anything further.
package ebpf

//go:generate ./gen.sh
