#!/usr/bin/env bash
# Regenerates the CO-RE BPF objects and their Go bindings in this package.
#
# clang is not installed on the host, so this script builds a small Debian
# image with clang/llvm/libbpf-dev (gen/Dockerfile) and runs bpf2go on the
# host Go toolchain, but with `clang`/`llvm-strip` on PATH pointing at
# wrapper scripts that shell out to that image (`docker run`) instead of the
# real binaries. bpf2go itself still runs natively; only the two compiler
# invocations it makes are containerized. This needs the current directory
# mounted into the container at the same absolute path, since bpf2go invokes
# the compiler with absolute source/output paths.
#
# vmlinux.h is generated separately, on the host, from the running kernel's
# BTF via bpftool (not from inside the container, since the container has
# neither bpftool nor /sys/kernel/btf/vmlinux). It is not committed: it is
# only a compile-time input, regenerated by this script, and kept out of the
# repo by bpf/.gitignore.
#
# Usage: internal/sensor/ebpf/gen.sh
# Requires: docker, and either /usr/sbin/bpftool or bpftool on PATH, and
# read access to /sys/kernel/btf/vmlinux.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"
PKG_DIR="$(pwd)"
REPO_ROOT="$(cd ../../.. && pwd)"

IMAGE="kestrelynx-bpf-builder:bookworm-20250908"

BPFTOOL="$(command -v bpftool || echo /usr/sbin/bpftool)"
if [ ! -x "$BPFTOOL" ]; then
	echo "gen.sh: bpftool not found (looked on PATH and at /usr/sbin/bpftool)" >&2
	exit 1
fi
if [ ! -r /sys/kernel/btf/vmlinux ]; then
	echo "gen.sh: /sys/kernel/btf/vmlinux is not readable; cannot regenerate vmlinux.h" >&2
	exit 1
fi

echo "gen.sh: building $IMAGE" >&2
docker build -t "$IMAGE" gen >&2

echo "gen.sh: generating bpf/vmlinux.h from the running kernel's BTF" >&2
"$BPFTOOL" btf dump file /sys/kernel/btf/vmlinux format c > bpf/vmlinux.h

TMP_BIN="$(mktemp -d)"
trap 'rm -rf "$TMP_BIN"' EXIT

cat > "$TMP_BIN/clang" <<EOF
#!/bin/sh
exec docker run --rm -u "\$(id -u):\$(id -g)" \\
	-v "$REPO_ROOT:$REPO_ROOT" -w "\$PWD" "$IMAGE" clang "\$@"
EOF
cat > "$TMP_BIN/llvm-strip" <<EOF
#!/bin/sh
exec docker run --rm -u "\$(id -u):\$(id -g)" \\
	-v "$REPO_ROOT:$REPO_ROOT" -w "\$PWD" "$IMAGE" llvm-strip "\$@"
EOF
chmod +x "$TMP_BIN/clang" "$TMP_BIN/llvm-strip"

echo "gen.sh: running bpf2go (target amd64,arm64)" >&2
cd "$PKG_DIR"
PATH="$TMP_BIN:$PATH" GOPACKAGE=ebpf go run github.com/cilium/ebpf/cmd/bpf2go \
	-cc clang \
	-target amd64,arm64 \
	-type kl_event \
	-cflags "-Wall -Werror -I$PKG_DIR/bpf" \
	kestrelynxebpf bpf/kestrelynx.c

echo "gen.sh: done" >&2
