// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type kestrelynxebpfKlAttemptKey struct {
	_        structs.HostLayout
	CgroupId uint64
	Dev      uint64
	Ino      uint64
}

type kestrelynxebpfKlEvent struct {
	_               structs.HostLayout
	CgroupId        uint64
	MntNsId         uint64
	UserNsId        uint64
	Tgid            uint64
	StartBoottimeNs uint64
	CapEffective    uint64
	Dev             uint64
	Ino             uint64
	RootDev         uint64
	RootIno         uint64
	KtimeNs         uint64
	Euid            uint32
	Prot            uint32
	Kind            uint8
	PathTruncated   uint8
	PathLen         uint16
	Path            [256]uint8
	_               [4]byte
}

type kestrelynxebpfKlPathKey struct {
	_       structs.HostLayout
	MntNsId uint32
	_       [4]byte
	RootDev uint64
	RootIno uint64
	Dev     uint64
	Ino     uint64
}

type kestrelynxebpfKlUsageKey struct {
	_            structs.HostLayout
	CgroupId     uint64
	Dev          uint64
	Ino          uint64
	CapEffective uint64
	MntNsId      uint32
	Kind         uint8
	EuidIsRoot   uint8
	InInitUserns uint8
	_            [1]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	kestrelynxebpfMapKlDedupAttempt   = "kl_dedup_attempt"
	kestrelynxebpfMapKlDedupPath      = "kl_dedup_path"
	kestrelynxebpfMapKlDedupUsage     = "kl_dedup_usage"
	kestrelynxebpfMapKlEvents         = "kl_events"
	kestrelynxebpfMapKlExcludedCgroup = "kl_excluded_cgroup"
	kestrelynxebpfMapKlLostByCgroup   = "kl_lost_by_cgroup"
	kestrelynxebpfMapKlLostEvents     = "kl_lost_events"
	kestrelynxebpfMapKlSelftest       = "kl_selftest"
	kestrelynxebpfProgKlCgroupMkdir   = "kl_cgroup_mkdir"
	kestrelynxebpfProgKlExecSuccess   = "kl_exec_success"
	kestrelynxebpfProgKlFileOpen      = "kl_file_open"
	kestrelynxebpfProgKlMmapOpen      = "kl_mmap_open"
	kestrelynxebpfProgKlMmapSuccess   = "kl_mmap_success"
	kestrelynxebpfVarUnusedKlEvent    = "unused_kl_event"
)

// loadKestrelynxebpf returns the embedded CollectionSpec for kestrelynxebpf.
func loadKestrelynxebpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KestrelynxebpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load kestrelynxebpf: %w", err)
	}

	return spec, err
}

// loadKestrelynxebpfObjects loads kestrelynxebpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*kestrelynxebpfObjects
//	*kestrelynxebpfPrograms
//	*kestrelynxebpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadKestrelynxebpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadKestrelynxebpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// kestrelynxebpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kestrelynxebpfSpecs struct {
	kestrelynxebpfProgramSpecs
	kestrelynxebpfMapSpecs
	kestrelynxebpfVariableSpecs
}

// kestrelynxebpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kestrelynxebpfProgramSpecs struct {
	KlCgroupMkdir *ebpf.ProgramSpec `ebpf:"kl_cgroup_mkdir"`
	KlExecSuccess *ebpf.ProgramSpec `ebpf:"kl_exec_success"`
	KlFileOpen    *ebpf.ProgramSpec `ebpf:"kl_file_open"`
	KlMmapOpen    *ebpf.ProgramSpec `ebpf:"kl_mmap_open"`
	KlMmapSuccess *ebpf.ProgramSpec `ebpf:"kl_mmap_success"`
}

// kestrelynxebpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kestrelynxebpfMapSpecs struct {
	KlDedupAttempt   *ebpf.MapSpec `ebpf:"kl_dedup_attempt"`
	KlDedupPath      *ebpf.MapSpec `ebpf:"kl_dedup_path"`
	KlDedupUsage     *ebpf.MapSpec `ebpf:"kl_dedup_usage"`
	KlEvents         *ebpf.MapSpec `ebpf:"kl_events"`
	KlExcludedCgroup *ebpf.MapSpec `ebpf:"kl_excluded_cgroup"`
	KlLostByCgroup   *ebpf.MapSpec `ebpf:"kl_lost_by_cgroup"`
	KlLostEvents     *ebpf.MapSpec `ebpf:"kl_lost_events"`
	KlSelftest       *ebpf.MapSpec `ebpf:"kl_selftest"`
}

// kestrelynxebpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kestrelynxebpfVariableSpecs struct {
	UnusedKlEvent *ebpf.VariableSpec `ebpf:"unused_kl_event"`
}

// kestrelynxebpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadKestrelynxebpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type kestrelynxebpfObjects struct {
	kestrelynxebpfPrograms
	kestrelynxebpfMaps
	kestrelynxebpfVariables
}

func (o *kestrelynxebpfObjects) Close() error {
	return _KestrelynxebpfClose(
		&o.kestrelynxebpfPrograms,
		&o.kestrelynxebpfMaps,
	)
}

// kestrelynxebpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadKestrelynxebpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type kestrelynxebpfMaps struct {
	KlDedupAttempt   *ebpf.Map `ebpf:"kl_dedup_attempt"`
	KlDedupPath      *ebpf.Map `ebpf:"kl_dedup_path"`
	KlDedupUsage     *ebpf.Map `ebpf:"kl_dedup_usage"`
	KlEvents         *ebpf.Map `ebpf:"kl_events"`
	KlExcludedCgroup *ebpf.Map `ebpf:"kl_excluded_cgroup"`
	KlLostByCgroup   *ebpf.Map `ebpf:"kl_lost_by_cgroup"`
	KlLostEvents     *ebpf.Map `ebpf:"kl_lost_events"`
	KlSelftest       *ebpf.Map `ebpf:"kl_selftest"`
}

func (m *kestrelynxebpfMaps) Close() error {
	return _KestrelynxebpfClose(
		m.KlDedupAttempt,
		m.KlDedupPath,
		m.KlDedupUsage,
		m.KlEvents,
		m.KlExcludedCgroup,
		m.KlLostByCgroup,
		m.KlLostEvents,
		m.KlSelftest,
	)
}

// kestrelynxebpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadKestrelynxebpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type kestrelynxebpfVariables struct {
	UnusedKlEvent *ebpf.Variable `ebpf:"unused_kl_event"`
}

// kestrelynxebpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadKestrelynxebpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type kestrelynxebpfPrograms struct {
	KlCgroupMkdir *ebpf.Program `ebpf:"kl_cgroup_mkdir"`
	KlExecSuccess *ebpf.Program `ebpf:"kl_exec_success"`
	KlFileOpen    *ebpf.Program `ebpf:"kl_file_open"`
	KlMmapOpen    *ebpf.Program `ebpf:"kl_mmap_open"`
	KlMmapSuccess *ebpf.Program `ebpf:"kl_mmap_success"`
}

func (p *kestrelynxebpfPrograms) Close() error {
	return _KestrelynxebpfClose(
		p.KlCgroupMkdir,
		p.KlExecSuccess,
		p.KlFileOpen,
		p.KlMmapOpen,
		p.KlMmapSuccess,
	)
}

func _KestrelynxebpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kestrelynxebpf_x86_bpfel.o
var _KestrelynxebpfBytes []byte
